apiVersion: extensions/v1beta1 
kind: Deployment 
metadata:
  name: testuport
spec:
  replicas: 1
  strategy:
    type: Recreate  # Delete the existing pods before creating the new one.
                    # This way we don't have two bots connected at once, which
                    # is not desired for custom integrations.
                    #
                    # The RollingUpdate strategy should be used for Slack Apps,
                    # which need to scale to multiple teams.
  template:
    metadata:
      labels:
        app: testuport
    spec:
      containers:
      - name: master
        image: gcr.io/testbot-168718/attester:v1  # Replace PROJECT_ID
        ports:
        no- hostPort: 8081
          containerPort: 8081
          protocol: TCP
        env:
        - name: ATTESTER_APPNAME
          valueFrom:
            secretKeyRef:
              name: attester
              key: attester_appname.txt
        - name: ATTESTER_PRK
          valueFrom:
            secretKeyRef:
              name: attester
              key: attester_prk.txtu
        - name: ATTESTER_ADDRESS
          valueFrom:
            secretKeyRef:
              name: attester
              key: attester_address.txt            
              

